### ISSUE TITLE
Compile error with `gcc version 10.1.0 (GCC)`

### ISSUE THREAD

**Issue by vvrein** [ohwgiles/laminar#123]
Hi, thank you for such a nice project!

Error rises up when I've tried to compile laminar on my main (amd64) pc.
But it successfully compiles on orange pi one. 
The only difference I found -- was compiler version.

```
orpi one (arm)      -- gcc version 9.3.0 (GCC) 
main pc  (amd64) -- gcc version 10.1.0 (GCC)
```

I followed compiler instructions, and "monkey fixed" the compilation.
Since I don't know C/C++ - I'm not opening the pr, since there might be better way  to fix this :eyes:  

<details><summary>Compile log</summary>

```make
| make
Scanning dependencies of target laminarc
[  2%] Building CXX object CMakeFiles/laminarc.dir/src/client.cpp.o
[  5%] Building CXX object CMakeFiles/laminarc.dir/laminar.capnp.c++.o
[  7%] Linking CXX executable laminarc
[ 10%] Built target laminarc
[ 13%] Building CXX object CMakeFiles/laminard.dir/src/conf.cpp.o
In file included from /home/vrein/data/local/builds/laminar/src/conf.cpp:19:
/home/vrein/data/local/builds/laminar/src/conf.h:24:50: error: ‘string’ is not a member of ‘std’
   24 | class StringMap : public std::unordered_map<std::string, std::string> {
      |                                                  ^~~~~~
/home/vrein/data/local/builds/laminar/src/conf.h:23:1: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
   22 | #include <unordered_map>
  +++ |+#include <string>
   23 |
/home/vrein/data/local/builds/laminar/src/conf.h:24:50: error: ‘string’ is not a member of ‘std’
   24 | class StringMap : public std::unordered_map<std::string, std::string> {
      |                                                  ^~~~~~
/home/vrein/data/local/builds/laminar/src/conf.h:24:50: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
/home/vrein/data/local/builds/laminar/src/conf.h:24:63: error: ‘string’ is not a member of ‘std’
   24 | class StringMap : public std::unordered_map<std::string, std::string> {
      |                                                               ^~~~~~
/home/vrein/data/local/builds/laminar/src/conf.h:24:63: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
/home/vrein/data/local/builds/laminar/src/conf.h:24:63: error: ‘string’ is not a member of ‘std’
/home/vrein/data/local/builds/laminar/src/conf.h:24:63: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
/home/vrein/data/local/builds/laminar/src/conf.h:24:69: error: template argument 1 is invalid
   24 | class StringMap : public std::unordered_map<std::string, std::string> {
      |                                                                     ^
/home/vrein/data/local/builds/laminar/src/conf.h:24:69: error: template argument 2 is invalid
/home/vrein/data/local/builds/laminar/src/conf.h:24:69: error: template argument 3 is invalid
/home/vrein/data/local/builds/laminar/src/conf.h:24:69: error: template argument 4 is invalid
/home/vrein/data/local/builds/laminar/src/conf.h:24:69: error: template argument 5 is invalid
/home/vrein/data/local/builds/laminar/src/conf.h:27:16: error: ‘std::string’ has not been declared
   27 |     T get(std::string key, T fallback = T()) {
      |                ^~~~~~
/home/vrein/data/local/builds/laminar/src/conf.h:33:20: error: ‘std::string’ has not been declared
   33 |     T convert(std::string e) { return e; }
      |                    ^~~~~~
/home/vrein/data/local/builds/laminar/src/conf.h: In member function ‘T StringMap::get(int, T)’:
/home/vrein/data/local/builds/laminar/src/conf.h:28:19: error: there are no arguments to ‘find’ that depend on a template parameter, so a declaration of ‘find’ must be available [-fpermissive]
   28 |         auto it = find(key);
      |                   ^~~~
/home/vrein/data/local/builds/laminar/src/conf.h:28:19: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/vrein/data/local/builds/laminar/src/conf.h:29:22: error: there are no arguments to ‘end’ that depend on a template parameter, so a declaration of ‘end’ must be available [-fpermissive]
   29 |         return it != end() ? convert<T>(it->second) : fallback;
      |                      ^~~
/home/vrein/data/local/builds/laminar/src/conf.h: At global scope:
/home/vrein/data/local/builds/laminar/src/conf.h:36:5: error: ‘int StringMap::convert’ is not a static data member of ‘class StringMap’
   36 | int StringMap::convert(std::string e);
      |     ^~~~~~~~~
/home/vrein/data/local/builds/laminar/src/conf.h:36:29: error: ‘string’ is not a member of ‘std’
   36 | int StringMap::convert(std::string e);
      |                             ^~~~~~
/home/vrein/data/local/builds/laminar/src/conf.h:36:29: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
/home/vrein/data/local/builds/laminar/src/conf.h:36:5: warning: too many template headers for ‘StringMap::convert’ (should be 0)
   36 | int StringMap::convert(std::string e);
      |     ^~~~~~~~~
/home/vrein/data/local/builds/laminar/src/conf.cpp:24:5: error: template-id ‘convert<>’ for ‘int StringMap::convert(std::string)’ does not match any template declaration
   24 | int StringMap::convert(std::string e) { return atoi(e.c_str()); }
      |     ^~~~~~~~~
In file included from /home/vrein/data/local/builds/laminar/src/conf.cpp:19:
/home/vrein/data/local/builds/laminar/src/conf.h:33:7: note: candidate is: ‘template<class T> T StringMap::convert(int)’
   33 |     T convert(std::string e) { return e; }
      |       ^~~~~~~
/home/vrein/data/local/builds/laminar/src/conf.cpp: In function ‘StringMap parseConfFile(const char*)’:
/home/vrein/data/local/builds/laminar/src/conf.cpp:35:20: error: ‘class StringMap’ has no member named ‘emplace’
   35 |             result.emplace(line.substr(0, p), line.substr(p+1));
      |                    ^~~~~~~
make[2]: *** [CMakeFiles/laminard.dir/build.make:184: CMakeFiles/laminard.dir/src/conf.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:125: CMakeFiles/laminard.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

</details>

<details><summary>Fix</summary>

```diff
| git diff
diff --git a/src/conf.h b/src/conf.h
index cdabf95..984175f 100644
--- a/src/conf.h
+++ b/src/conf.h
@@ -20,6 +20,7 @@
 #define LAMINAR_CONF_H_

 #include <unordered_map>
+#include <string>

 class StringMap : public std::unordered_map<std::string, std::string> {
 public:
diff --git a/src/server.h b/src/server.h
index 048f388..1e57d94 100644
--- a/src/server.h
+++ b/src/server.h
@@ -21,6 +21,7 @@

 #include <kj/async-io.h>
 #include <kj/compat/http.h>
+#include <src/run.h>
 #include <capnp/message.h>
 #include <capnp/capability.h>
 #include <functional>
```

</details>

With this fix, code both compiles on orpi (gcc version 9.3.0) & desktop pc (gcc version 10.1.0)

**Comment by ohwgiles** [comment]
Hi, thanks for the heads up on this. Fix pushed.
