### ISSUE TITLE
Some version dependencies when building? Doesn't work on Ubuntu 18.04 at least?

### ISSUE THREAD

**Issue by fingon** [ohwgiles/laminar#65]
on Ubuntu LTS (18.04):

First of all, I think I got most deps with following:

> sudo apt-get install capnproto libcapnp-dev rapidjson-dev sqlite libboost-dev

cmake ran fine. make on the other hand..

```

mstenber@mstenber-u18 ~/git/laminar>make
[  2%] Generating laminar.capnp.c++, laminar.capnp.h
Scanning dependencies of target laminarc
[  5%] Building CXX object CMakeFiles/laminarc.dir/src/client.cpp.o
/home/mstenber/git/laminar/src/client.cpp: In function ‘int main(int, char**)’:
/home/mstenber/git/laminar/src/client.cpp:136:12: error: ‘class kj::TaskSet’ has no member named ‘onEmpty’
         ts.onEmpty().wait(waitScope);
            ^~~~~~~
/home/mstenber/git/laminar/src/client.cpp:160:12: error: ‘class kj::TaskSet’ has no member named ‘onEmpty’
         ts.onEmpty().wait(waitScope);
            ^~~~~~~
CMakeFiles/laminarc.dir/build.make:69: recipe for target 'CMakeFiles/laminarc.dir/src/client.cpp.o' failed
make[2]: *** [CMakeFiles/laminarc.dir/src/client.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/laminarc.dir/all' failed
make[1]: *** [CMakeFiles/laminarc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2


```

**Comment by ohwgiles** [comment]
This is because I use features only in the latest [capnproto](https://github.com/capnproto/capnproto). It's written `capnproto (git)` in the README, but I admit that's not very clear. I've just noticed that version 0.7 [was released](https://github.com/capnproto/capnproto/releases/tag/v0.7.0) a week ago, which would also work. Until that makes it into Ubuntu I'm afraid you'll need to build it yourself. For some guidelines you could take a look at [docker-build-debian.sh](https://github.com/ohwgiles/laminar/blob/master/docker-build-debian.sh)
